### ISSUE TITLE
when to release the code

### ISSUE THREAD

**Issue by tornadomeet** [hehefan/PointRNN#3]
hello, @hehefan   thanks for your paper, i'm interested in the implementation  ```EMD``` loss , so when do you share your code?  thanks.

**Comment by hehefan** [comment]
Hi, @tornadomeet. I am trying to make the code simple and easy to understand.  The code will be released soon. You can refer to https://github.com/charlesq34/pointnet-autoencoder/blob/master/tf_ops/approxmatch/tf_approxmatch.py for the implementation of EMD, which is exactly used in our code.

**Comment by tornadomeet** [comment]
great, thanks @hehefan
