### ISSUE TITLE
Argoverse Question

### ISSUE THREAD

**Issue by pedro-dm-gomes** [hehefan/PointRNN#5]
Hello @hehefan ,

First thank you for the work and to make it available!

I am having difficulties loading the argoverse dateset.
The argoverse dateset I downloaded and extracted is in cvs format, it appears I should convert it to npy file in order to load to the program.

Could you explain how do you extracted and preprocessed the Argoverse dataset, in order to run the  "train-argo-nu.py". 

Thank you

**Comment by hehefan** [comment]
Hi @pedro-dm-gomes,

First, you need to download the [Argoverse 3D Tracking](https://www.argoverse.org/data.html#download-link) data. 
Second, extract files from the data. You will find the point cloud frames in the "lidar" folder. 

Best regards.

**Comment by hehefan** [comment]
@pedro-dm-gomes The point cloud frames are .ply files. You can use [pyntcloud](https://pyntcloud.readthedocs.io/en/latest/PyntCloud.html) or [open3d](http://www.open3d.org/docs/release/tutorial/Basic/working_with_numpy.html) to read them.

**Comment by pedro-dm-gomes** [comment]
Thank you very much!
I was looking at the wrong data (the Argoverse Motion Forecasting)
